name: Run tests

on:
  push:
    branches:
      - master

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 7.3
          - php: 8.0
          - php: 8.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, fileinfo
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: env-setup
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.env-setup.outputs.dir }}
          key: php-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: |
          composer update --prefer-source --no-interaction --no-suggest --no-plugins
      - name: Execute tests
        run: vendor/bin/phpunit -c phpunit.xml

